config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  post '/email', to: 'home#create_email'

  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.last(5).reverse
  end

  def create_email
    @info = {name: params[:name], email: params[:email], message: params[:message]}
    
    ContactMailer.contact_email(@info)
    flash[:notice] = "Thank you for the message!"
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def show
    @post = Post.find_by(params[:id])
    render :layout => false
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.haml
- flash.each do |name, msg|
  %a.close{"data-dismiss" => "alert"} ×
  = content_tag :div, msg, class: "alert alert-info"
  - flash.clear

app/views/application/_nav.html.haml
#nav_wrapper
  #logo
    %a
      
  #nav
    %ul
      %li
        %a{ href: 'home', class: "active", data: { scroll_to_anchor: 'home'}}
          Home
      %li
        %a{ href: 'about', data: { scroll_to_anchor: 'about'}}
          About
      %li
        %a{ href: 'projects', data: { scroll_to_anchor: 'projects'}}
          Projects
      %li
        %a{ href: 'blog', data: { scroll_to_anchor: 'blog'}}
          Blog
      %li
        %a{ href: 'contact', data: { scroll_to_anchor: 'contact'}}
          Contact

app/views/home/_about.html.haml
%a{ name: 'about' }
#about_div_wrapper
  .content
    %h1#about_h1_style
      About
    %p#about_p1_style
      I am a spirited, jubilant young developer that is looking for employment as a Ruby on Rails developer for a team that moves fast and has fun doing it!
    %p#about_p2_style
      I am a very impassioned individual that is looking to grow as a developer. I am looking for a company that is collaborative in nature and one with which I can grow. I enjoy energetic, fast paced environments where teams are very driven to succeed but has fun doing it! I am a paladin when it comes to the company I work for and will devote everything I have to see it succeed, including: nights, weekends, working on tasks such as analytics and marketing, whatever it takes to get things moving forward.
    %p#about_p2_style
      Some of my awesome skills:
    %ul#about_ul_style
      %li
        Ruby
      %li
        Rails
      %li
        JavaScript/jQuery
      %li
        HTML5/HAML
      %li
        CSS3/SCSS
      %li
        PostgreSQL
      %li
        Git
      %li
        RSpec
      %li
        Heroku

app/views/home/_blog.html.haml
%a{ name: 'blog' }
#blog_div_wrapper
  .content
    %h1#blog_h1_style
      Blog
    %div
      - @posts.each do |post|
        %p{  "data-target" => "#post_#{post.id}", "data-toggle" => "modal"}
          = link_to post.id, post_path(post)

        = render "posts/post", post: post

app/views/home/_contact.html.haml
%a{ name: 'contact' }
#contact_div_wrapper
  .content
    %h1#contact_h1_style
      Contact
    #contact_links_wrapper
      %a{ href: 'https://www.linkedin.com/in/brent-palmer-096b2a6b'}
        .fa.fa-linkedin-square

      %a{ href: 'https://github.com/BrentPalmer'}
        .fa.fa-github-square
    #contact_form_wrapper
      = form_tag email_path, method: 'post', class: 'contact_form_style' do
        .form-group
          = text_field_tag :name, nil, placeholder: "Name", class: 'form-control'
        .form-group
          = email_field_tag :email, nil, placeholder: "Email", class: 'form-control'
        .form-group
          = text_area_tag :message, nil, placeholder: "Message", class: 'form-control'
        .form-group
          = submit_tag "Send", class: 'btn btn-primary btn-lg'

app/views/home/_home.html.haml
%a{ name: 'home' }
#home_div_wrapper
  .content
    #home_content
      %h1
        Brent Palmer
      %h3
        Web Developer

app/views/home/_projects.html.haml
%a{ name: 'projects' }
#projects_div_wrapper
  .content
  #projects_wrapper
    %h1#project_h1_style
      Projects
    %div.project 
      %p
        project 1
    %div.project 
      %p
        project 2
    %div.project 
      %p
        project 3

app/views/home/index.html.haml
= render 'application/nav'
= render 'home'
= render 'about'
= render 'projects'
= render 'blog'
= render 'contact'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Portfolio
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
    
    = stylesheet_link_tag "application", :media => "all"
    

    = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"
    = javascript_include_tag "application"

    = csrf_meta_tags
  %body

    = yield

app/views/posts/_post.html.haml
.modal.fade{ id: "#post_#{post.id}", data: { remote: main_app.post_path( id: post.id ) } }
  .modal-dialog
    .modal-content

app/views/posts/new.html.haml
.container
	.row
		.col-sm-10.col-sm-offset-1
			%h1#blog_h1_style
				New Post
			= form_for @post do |f|
				.form-group
					= f.label :title
					= f.text_field :title, class: 'form-control'
				.form-group
					= f.label :content
					= f.text_area :content, class: 'form-control', rows: "15"
				.form-group.pull-right
					=f.submit "create", class: "btn btn-primary"

app/views/posts/show.html.haml
.modal-title
  Hi
.modal-body
  Some text
.modal-footer